spring:
  datasource:
    url: jdbc:mysql://tmp-dev.cpmk2mq48bz1.ap-northeast-1.rds.amazonaws.com/hackathon
    username: root
    password: tjdans7706
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      maxFileSize: 200MB # ??? ?? ?? ???
      maxRequestSize: 300MB

cloud:
  aws:
    s3:
      bucket: temp-project
    region:
      static: ap-northeast-1
    stack:
      auto: false
    credentials:
      accessKey: AKIAYX3QZQKUDXAW4RNT
      secretKey: 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
